### PR TITLE
Problem Sets  Antonopoulos

### PR DESCRIPTION
**Pull request by antonopoulos**

### CODE REVIEW

**Comment by rickecon** [comment]
@antonopoulos . Good job.

**Comment by antonopoulos** [comment]
[PS_2_Antonopoulos.zip](https://github.com/rickecon/StructEst_W18/files/1650978/PS_2_Antonopoulos.zip)

**Comment by antonopoulos** [comment]
[PS3_Antonopoulos.zip](https://github.com/rickecon/StructEst_W18/files/1660841/PS3_Antonopoulos.zip)

**Comment by antonopoulos** [comment]
[PS4_Antonopoulos.zip](https://github.com/rickecon/StructEst_W18/files/1696384/PS4_Antonopoulos.zip)
PS4

**Comment by antonopoulos** [comment]
[PS5_Antonopoulos.zip](https://github.com/rickecon/StructEst_W18/files/1715550/PS5_Antonopoulos.zip)
PS5

**Pull request closed without merging**
